import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Edit2, ExternalLink, Bot, FileText, Tag, Zap, ChefHat, Plus, Star } from 'lucide-react';
import { Meal, Tier } from '../types';
import { getEffortColor, getMealTier, TIER_CONFIG } from '../utils';

interface MealDetailsModalProps {
  meal: Meal | null;
  onClose: () => void;
  onEdit: (meal: Meal) => void;
  onAdd: (meal: Meal) => void;
  onUpdateTier?: (mealId: string, tier: Tier) => void;
}

const MealDetailsModal: React.FC<MealDetailsModalProps> = ({ meal, onClose, onEdit, onAdd, onUpdateTier }) => {
  const [showSourceImage, setShowSourceImage] = useState(false);
  const [methodTab, setMethodTab] = useState<'standard' | 'thermomix'>('standard');
  const [showTierSelector, setShowTierSelector] = useState(false);

  if (!meal) return null;

  const hasThermomix = meal.thermomixMethod && meal.thermomixMethod.length > 0;
  const mealTier = getMealTier(meal);
  const tierConfig = TIER_CONFIG[mealTier];

  const renderSourceBadge = () => {
    const type = meal.sourceType || 'manual';
    switch (type) {
        case 'url':
            return meal.sourceUrl ? (
                 <a href={meal.sourceUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-primary-600 dark:text-primary-400 bg-primary-50 dark:bg-primary-950/50 px-3 py-2 rounded-lg hover:bg-primary-100 dark:hover:bg-primary-900/50 transition-colors text-sm font-medium w-fit">
                    <ExternalLink size={16} /> Source: Original Website
                </a>
            ) : null;
        case 'ai':
            return (
                <div className="flex items-center gap-2 text-purple-600 dark:text-purple-400 bg-purple-50 dark:bg-purple-950/50 px-3 py-2 rounded-lg text-sm font-medium w-fit">
                    <Bot size={16} /> Source: Generated by Chef AI
                </div>
            );
        case 'image':
            return (
                 <button onClick={() => setShowSourceImage(true)} className="flex items-center gap-2 text-primary dark:text-primary-400 bg-neutral-100 dark:bg-neutral-800 px-3 py-2 rounded-lg hover:bg-neutral-200 dark:hover:bg-neutral-700 transition-colors text-sm font-medium w-fit">
                    <FileText size={16} /> Source: View Recipe Scan
                </button>
            );
        default: return null;
    }
  };

  return (
    <AnimatePresence>
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-[70] flex justify-end"
      >
        {/* DEBUG: Added z-0 to ensure backdrop is below modal content */}
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="absolute inset-0 bg-black/20 backdrop-blur-sm z-0"
          onClick={onClose}
        />

        {/* DEBUG: Added z-10 to ensure modal content is above backdrop */}
        <motion.div 
          initial={{ x: '100%' }}
          animate={{ x: 0 }}
          exit={{ x: '100%' }}
          transition={{ type: "spring", damping: 25, stiffness: 300 }}
          className="relative z-10 w-full sm:max-w-md h-full bg-surface shadow-2xl flex flex-col overflow-hidden"
        >
          
          <div className="relative h-64 flex-none">
              <img src={meal.image} alt={meal.title} className="w-full h-full object-cover" />
              <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"></div>
              <motion.button 
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                onClick={onClose} 
                className="absolute top-4 right-4 bg-black/20 hover:bg-black/40 text-white p-2 rounded-full backdrop-blur-md"
              >
                  <X size={20} />
              </motion.button>
              <div className="absolute bottom-4 left-4 right-4 text-white">
                  <h2 className="text-2xl font-display font-bold leading-tight mb-2">{meal.title}</h2>
                  <div className="flex flex-wrap items-center gap-2 text-sm font-medium opacity-90">
                      <span 
                        onClick={() => setShowTierSelector(!showTierSelector)}
                        className={`flex items-center gap-1.5 px-2 py-0.5 rounded-md backdrop-blur-sm cursor-pointer hover:scale-105 transition-transform ${tierConfig.badgeClass}`}
                      >
                          <Star size={12} />
                          <span className="capitalize">{tierConfig.label}</span>
                      </span>
                      <span className="flex items-center gap-1.5 bg-white/20 px-2 py-0.5 rounded-md backdrop-blur-sm">
                          <div className={`w-2 h-2 rounded-full ${getEffortColor(meal.effort)}`} />
                          <span className="capitalize">{meal.effort} Effort</span>
                      </span>
                      <span className="bg-black/40 px-2 py-0.5 rounded-md backdrop-blur-sm">{meal.protein}</span>
                  </div>
                  {showTierSelector && onUpdateTier && (
                    <div className="absolute bottom-16 left-4 bg-white dark:bg-neutral-800 rounded-lg shadow-xl p-2 z-10 flex flex-col gap-1">
                      {(Object.keys(TIER_CONFIG) as Tier[]).map((tier) => {
                        const config = TIER_CONFIG[tier];
                        return (
                          <button
                            key={tier}
                            onClick={() => {
                              onUpdateTier(meal.id, tier);
                              setShowTierSelector(false);
                            }}
                            className={`flex items-center gap-2 px-3 py-2 rounded-md text-sm font-medium transition-colors ${tier === mealTier ? config.badgeClass : 'hover:bg-neutral-100 dark:hover:bg-neutral-700'}`}
                          >
                            <Star size={14} />
                            <span>{config.label}</span>
                          </button>
                        );
                      })}
                    </div>
                  )}
              </div>
          </div>

          <div className="flex-1 overflow-y-auto p-6 space-y-8 custom-scrollbar">
              <div className="flex flex-col gap-4">
                  {renderSourceBadge()}
                  {meal.tags && meal.tags.length > 0 && (
                      <div className="flex flex-wrap gap-2">
                          {meal.tags.map((tag, i) => (
                              <motion.div 
                                key={i}
                                initial={{ opacity: 0, scale: 0.8 }}
                                animate={{ opacity: 1, scale: 1 }}
                                transition={{ delay: i * 0.05 }}
                                className="text-xs font-semibold text-secondary bg-neutral-100 dark:bg-neutral-800 px-2 py-1 rounded-full border border-border flex items-center gap-1"
                              >
                                  <Tag size={12} className="opacity-50"/> {tag}
                              </motion.div>
                          ))}
                      </div>
                  )}
              </div>

              {meal.description && <p className="text-secondary italic leading-relaxed border-l-2 border-primary-300 dark:border-primary-700 pl-4">{meal.description}</p>}

              <div>
                  <h3 className="text-lg font-display font-bold text-primary mb-3 border-b border-border pb-2">Ingredients</h3>
                  {meal.ingredients && meal.ingredients.length > 0 ? (
                      <ul className="space-y-2">
                          {meal.ingredients.map((ing, i) => (
                              <motion.li 
                                key={i} 
                                initial={{ opacity: 0, x: -10 }}
                                animate={{ opacity: 1, x: 0 }}
                                transition={{ delay: i * 0.03 }}
                                className="flex items-start gap-3 text-primary"
                              >
                                  <span className="w-1.5 h-1.5 rounded-full bg-primary-400 mt-2 flex-none" />
                                  <span className="flex-1 leading-relaxed">{ing}</span>
                              </motion.li>
                          ))}
                      </ul>
                  ) : <p className="text-secondary italic text-sm">No ingredients listed.</p>}
              </div>

              <div>
                  <div className="flex items-center justify-between mb-3 border-b border-border pb-1">
                      <h3 className="text-lg font-display font-bold text-primary">Method</h3>
                      {hasThermomix && (
                          <div className="flex bg-neutral-100 dark:bg-neutral-800 p-1 rounded-lg">
                              <motion.button 
                                whileHover={{ scale: 1.05 }}
                                whileTap={{ scale: 0.95 }}
                                onClick={() => setMethodTab('standard')}
                                className={`p-1.5 rounded-md transition-all ${methodTab === 'standard' ? 'bg-surface shadow-sm text-primary' : 'text-secondary'}`}
                                title="Standard Method"
                              >
                                  <ChefHat size={16} />
                              </motion.button>
                              <motion.button 
                                whileHover={{ scale: 1.05 }}
                                whileTap={{ scale: 0.95 }}
                                onClick={() => setMethodTab('thermomix')}
                                className={`p-1.5 rounded-md transition-all ${methodTab === 'thermomix' ? 'bg-secondary-500 shadow-sm text-white' : 'text-secondary'}`}
                                title="Thermomix Mode"
                              >
                                  <Zap size={16} />
                              </motion.button>
                          </div>
                      )}
                  </div>

                  <AnimatePresence mode="wait">
                    {methodTab === 'standard' ? (
                        <motion.div
                          key="standard"
                          initial={{ opacity: 0, x: -10 }}
                          animate={{ opacity: 1, x: 0 }}
                          exit={{ opacity: 0, x: 10 }}
                        >
                          {meal.method && meal.method.length > 0 ? (
                              <ol className="space-y-4">
                                  {meal.method.map((step, i) => (
                                      <motion.li 
                                        key={i} 
                                        initial={{ opacity: 0, x: -10 }}
                                        animate={{ opacity: 1, x: 0 }}
                                        transition={{ delay: i * 0.05 }}
                                        className="flex gap-4 text-primary"
                                      >
                                          <span className="font-bold text-primary-500 flex-none">{i + 1}.</span>
                                          <span className="leading-relaxed">{step}</span>
                                      </motion.li>
                                  ))}
                              </ol>
                          ) : <p className="text-secondary italic text-sm">No instructions listed.</p>}
                        </motion.div>
                    ) : (
                        <motion.ol 
                          key="thermomix"
                          initial={{ opacity: 0, x: 10 }}
                          animate={{ opacity: 1, x: 0 }}
                          exit={{ opacity: 0, x: -10 }}
                          className="space-y-4 bg-secondary-50/30 dark:bg-secondary-950/30 p-4 rounded-xl border border-secondary-200 dark:border-secondary-800"
                        >
                            {meal.thermomixMethod?.map((step, i) => (
                                <motion.li 
                                  key={i} 
                                  initial={{ opacity: 0, x: 10 }}
                                  animate={{ opacity: 1, x: 0 }}
                                  transition={{ delay: i * 0.05 }}
                                  className="flex gap-4 text-secondary-900 dark:text-secondary-100"
                                >
                                    <Zap size={14} className="mt-1 flex-none text-secondary-600 dark:text-secondary-400" />
                                    <span className="leading-relaxed text-sm">{step}</span>
                                </motion.li>
                            ))}
                        </motion.ol>
                    )}
                  </AnimatePresence>
              </div>
          </div>

          <div className="p-4 border-t border-border bg-neutral-50 dark:bg-neutral-900 flex justify-between items-center gap-2">
               <motion.button 
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  onClick={() => onAdd(meal)} 
                  className="flex-1 bg-primary-600 text-white px-4 py-3 rounded-xl font-bold text-sm hover:bg-primary-700 transition-colors flex items-center justify-center gap-2"
               >
                  <Plus size={16} /> Add to Week
               </motion.button>
               <motion.button 
                  whileHover={{ scale: 1.1 }}
                  whileTap={{ scale: 0.9 }}
                  onClick={() => onEdit(meal)} 
                  className="p-3 text-secondary hover:text-primary hover:bg-neutral-200 dark:hover:bg-neutral-800 rounded-xl transition-colors bg-neutral-100 dark:bg-neutral-800"
                  title="Edit Meal"
               >
                  <Edit2 size={18} />
               </motion.button>
          </div>
        </motion.div>

        <AnimatePresence>
          {showSourceImage && meal.sourceImage && (
              <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 z-[80] bg-black/90 flex flex-col"
              >
                 <div className="flex justify-between items-center p-4">
                    <span className="text-white font-medium">Original Scan</span>
                    <motion.button 
                      whileHover={{ scale: 1.1 }}
                      whileTap={{ scale: 0.9 }}
                      onClick={() => setShowSourceImage(false)} 
                      className="bg-white/10 hover:bg-white/20 text-white p-2 rounded-full"
                    >
                      <X size={24} />
                    </motion.button>
                 </div>
                 <div className="flex-1 overflow-auto flex items-center justify-center p-4">
                    <motion.img 
                      initial={{ scale: 0.9, opacity: 0 }}
                      animate={{ scale: 1, opacity: 1 }}
                      exit={{ scale: 0.9, opacity: 0 }}
                      src={meal.sourceImage} 
                      alt="Recipe Scan" 
                      className="max-w-full max-h-full rounded-lg shadow-2xl" 
                    />
                 </div>
              </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
    </AnimatePresence>
  );
};

export default MealDetailsModal;
