import React, { useState } from 'react';
import { X, Edit2, ExternalLink, Bot, FileText, Tag, Zap, ChefHat } from 'lucide-react';
import { Meal } from '../types';
import { getEffortColor } from '../utils';

interface MealDetailsModalProps {
  meal: Meal | null;
  onClose: () => void;
  onEdit: (meal: Meal) => void;
}

const MealDetailsModal: React.FC<MealDetailsModalProps> = ({ meal, onClose, onEdit }) => {
  const [showSourceImage, setShowSourceImage] = useState(false);
  const [methodTab, setMethodTab] = useState<'standard' | 'thermomix'>('standard');

  if (!meal) return null;

  const hasThermomix = meal.thermomixMethod && meal.thermomixMethod.length > 0;

  const renderSourceBadge = () => {
    const type = meal.sourceType || 'manual';
    switch (type) {
        case 'url':
            return meal.sourceUrl ? (
                 <a href={meal.sourceUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-brand-600 bg-brand-50 px-3 py-2 rounded-lg hover:bg-brand-100 transition-colors text-sm font-medium w-fit">
                    <ExternalLink size={16} /> Source: Original Website
                </a>
            ) : null;
        case 'ai':
            return (
                <div className="flex items-center gap-2 text-purple-600 bg-purple-50 px-3 py-2 rounded-lg text-sm font-medium w-fit">
                    <Bot size={16} /> Source: Generated by Chef AI
                </div>
            );
        case 'image':
            return (
                 <button onClick={() => setShowSourceImage(true)} className="flex items-center gap-2 text-slate-700 bg-gray-100 px-3 py-2 rounded-lg hover:bg-gray-200 transition-colors text-sm font-medium w-fit">
                    <FileText size={16} /> Source: View Recipe Scan
                </button>
            );
        default: return null;
    }
  };

  return (
    <div className="fixed inset-0 z-[70] flex justify-end pointer-events-none">
      <div className="absolute inset-0 bg-black/20 backdrop-blur-sm pointer-events-auto transition-opacity" onClick={onClose} />

      <div className="w-full sm:max-w-md h-full bg-white shadow-2xl pointer-events-auto transform transition-transform animate-in slide-in-from-right duration-300 flex flex-col overflow-hidden">
        
        <div className="relative h-64 flex-none">
            <img src={meal.image} alt={meal.title} className="w-full h-full object-cover" />
            <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"></div>
            <button onClick={onClose} className="absolute top-4 right-4 bg-black/20 hover:bg-black/40 text-white p-2 rounded-full backdrop-blur-md">
                <X size={20} />
            </button>
            <div className="absolute bottom-4 left-4 right-4 text-white">
                <h2 className="text-2xl font-bold leading-tight mb-2">{meal.title}</h2>
                <div className="flex flex-wrap items-center gap-2 text-sm font-medium opacity-90">
                    <span className="flex items-center gap-1.5 bg-white/20 px-2 py-0.5 rounded-md backdrop-blur-sm">
                        <div className={`w-2 h-2 rounded-full ${getEffortColor(meal.effort)}`} />
                        <span className="capitalize">{meal.effort} Effort</span>
                    </span>
                    <span className="bg-black/40 px-2 py-0.5 rounded-md backdrop-blur-sm">{meal.protein}</span>
                </div>
            </div>
        </div>

        <div className="flex-1 overflow-y-auto p-6 space-y-8">
            <div className="flex flex-col gap-4">
                {renderSourceBadge()}
                {meal.tags && meal.tags.length > 0 && (
                    <div className="flex flex-wrap gap-2">
                        {meal.tags.map((tag, i) => (
                            <div key={i} className="text-xs font-semibold text-gray-600 bg-gray-100 px-2 py-1 rounded-full border border-gray-200 flex items-center gap-1">
                                <Tag size={12} className="opacity-50"/> {tag}
                            </div>
                        ))}
                    </div>
                )}
            </div>

            {meal.description && <p className="text-gray-600 italic leading-relaxed border-l-2 border-brand-200 pl-4">{meal.description}</p>}

            <div>
                <h3 className="text-lg font-bold text-gray-900 mb-3 border-b border-gray-100 pb-2">Ingredients</h3>
                {meal.ingredients && meal.ingredients.length > 0 ? (
                    <ul className="space-y-2">
                        {meal.ingredients.map((ing, i) => (
                            <li key={i} className="flex items-start gap-3 text-gray-700">
                                <span className="w-1.5 h-1.5 rounded-full bg-brand-300 mt-2 flex-none" />
                                <span className="flex-1 leading-relaxed">{ing}</span>
                            </li>
                        ))}
                    </ul>
                ) : <p className="text-gray-400 italic text-sm">No ingredients listed.</p>}
            </div>

            <div>
                <div className="flex items-center justify-between mb-3 border-b border-gray-100 pb-1">
                    <h3 className="text-lg font-bold text-gray-900">Method</h3>
                    {hasThermomix && (
                        <div className="flex bg-gray-100 p-1 rounded-lg">
                            <button 
                                onClick={() => setMethodTab('standard')}
                                className={`p-1.5 rounded-md transition-all ${methodTab === 'standard' ? 'bg-white shadow-sm text-black' : 'text-gray-400'}`}
                                title="Standard Method"
                            >
                                <ChefHat size={16} />
                            </button>
                            <button 
                                onClick={() => setMethodTab('thermomix')}
                                className={`p-1.5 rounded-md transition-all ${methodTab === 'thermomix' ? 'bg-green-500 shadow-sm text-white' : 'text-gray-400'}`}
                                title="Thermomix Mode"
                            >
                                <Zap size={16} />
                            </button>
                        </div>
                    )}
                </div>

                {methodTab === 'standard' ? (
                    meal.method && meal.method.length > 0 ? (
                        <ol className="space-y-4">
                            {meal.method.map((step, i) => (
                                <li key={i} className="flex gap-4 text-gray-700">
                                    <span className="font-bold text-brand-500 flex-none">{i + 1}.</span>
                                    <span className="leading-relaxed">{step}</span>
                                </li>
                            ))}
                        </ol>
                    ) : <p className="text-gray-400 italic text-sm">No instructions listed.</p>
                ) : (
                    <ol className="space-y-4 bg-green-50/30 p-4 rounded-xl border border-green-100">
                        {meal.thermomixMethod?.map((step, i) => (
                            <li key={i} className="flex gap-4 text-green-900">
                                <Zap size={14} className="mt-1 flex-none text-green-600" />
                                <span className="leading-relaxed text-sm">{step}</span>
                            </li>
                        ))}
                    </ol>
                )}
            </div>
        </div>

        <div className="p-4 border-t border-gray-100 bg-gray-50 flex justify-between items-center text-xs text-gray-400">
            <span>Last cooked {new Date(meal.lastCooked).toLocaleDateString()}</span>
             <button onClick={() => onEdit(meal)} className="flex items-center gap-1 text-gray-600 hover:text-black font-medium px-3 py-2 hover:bg-gray-100 rounded-lg transition-colors">
                <Edit2 size={14} /> Edit Meal
            </button>
        </div>
      </div>

      {showSourceImage && meal.sourceImage && (
          <div className="fixed inset-0 z-[80] bg-black/90 flex flex-col pointer-events-auto animate-in fade-in duration-200">
             <div className="flex justify-between items-center p-4">
                <span className="text-white font-medium">Original Scan</span>
                <button onClick={() => setShowSourceImage(false)} className="bg-white/10 hover:bg-white/20 text-white p-2 rounded-full"><X size={24} /></button>
             </div>
             <div className="flex-1 overflow-auto flex items-center justify-center p-4">
                <img src={meal.sourceImage} alt="Recipe Scan" className="max-w-full max-h-full rounded-lg shadow-2xl" />
             </div>
          </div>
      )}
    </div>
  );
};

export default MealDetailsModal;